stages:
  - code-analysis
  - unit-tests

linting:
  image: docker-registry.upshift.redhat.com/ccx-dev/ccx-builder-py:latest
  stage: code-analysis
  except:
    - schedules
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip setuptools wheel
    - pip install -r requirements.txt
    - pip install -e .[dev]
  script:
    - pre-commit run --all
  after_script:
    - git diff
  tags:
    - shared


unit-py36:
  image: docker-registry.upshift.redhat.com/ccx-dev/ccx-builder-py:latest
  stage: unit-tests
  except:
    - schedules
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip setuptools wheel
    - pip install -r requirements.txt
    - pip install -e .[dev]
  script:
    - pytest
  tags:
    - shared
