exclude: "doc|research|demos"
repos:
- repo: https://github.com/psf/black
  rev: 21.5b0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: check-yaml
    language_version: python3
  - id: debug-statements
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v2.14.0
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.1
  hooks:
    - id: flake8
      language_version: python3
- repo: https://gitlab.com/pycqa/pydocstyle
  rev: 6.0.0
  hooks:
    - id: pydocstyle
      language_version: python3
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint ccx_data_pipeline test
#       language: system
#       types: [python]
