plugins:
  packages:
    - insights.specs.default
    - controller
    - ocp
    - pythonjsonlogger
    - pythonjsonlogger.jsonlogger
  configs:
    - name: ocp.config.telemeter.TelemeterServiceConfig
      enabled: false
service:
  extract_timeout:
  extract_tmp_dir:
  format: insights.formats._json.JsonFormat
  target_components: []
  consumer:
    name: controller.consumer.Consumer
    kwargs:
      incoming_topic: platform.upload.ccx
      group_id: ccx_data_pipeline_app
      bootstrap_servers:
        - "10.34.129.172:9092"

  downloader:
    name: controller.http_downloader.HTTPDownloader

  publisher:
    name: controller.publisher.Publisher
    kwargs:
      outgoing_topic: platform.results.ccx
      bootstrap_servers:
        - "10.34.129.172:9092"
  watchers: []

  logging:
    version: 1
    disable_existing_loggers: false
    handlers:
      default:
        level: DEBUG
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: json
        filters:
          - context_filter
    formatters:
      brief:
        format: "%(message)s"
      json:
        (): "pythonjsonlogger.jsonlogger.JsonFormatter"
        format: "%(levelname)s %(asctime)s %(name)s %(filename)s %(message)s"
    filters:
      context_filter:
        (): "controller.log_filter.LogFilter"
    root:
      handlers:
        - default
    loggers:
      insights_messaging:
        level: DEBUG
      insights:
        level: WARNING
      controller:
        level: DEBUG
