plugins:
    packages:
        - insights.specs.default
        - controller
configs: []
service:
    extract_timeout:
    extract_tmp_dir:
    format: insights.formats._json.JsonFormat
    target_components: []
    consumer:
        name: controller.consumer.Consumer
        kwargs:
            incoming_topic: platform.upload.ccx
            group_id: ccx_data_pipeline_app
            bootstrap_servers:
                - "10.34.129.172:9092"

    downloader:
        name: controller.minio_downloader.MinioDownloader
        kwargs:
            endpoint: "10.34.129.226:9000"
            access_key_env: "MINIOUSER"
            secret_key_env: "MINIOPASS"
            secure: false

    publisher:
        name: controller.publisher.Publisher
        kwargs:
            outgoing_topic: platform.results.ccx
            bootstrap_servers:
                - "10.34.129.172:9092"
    watchers: []
    logging:
        version: 1
        disable_existing_loggers: false
        handlers:
            default:
                level: DEBUG
                class: logging.StreamHandler
                stream: ext://sys.stdout
        root:
            handlers:
                - default
            level: WARNING
        loggers:
            controller:
                level: DEBUG
            insights_messaging:
                level: DEBUG
