plugins:
    packages:
        - insights.specs.default
        - controller
configs: []
service:
    extract_timeout:
    extract_tmp_dir:
    format: insights.formats._json.JsonFormat
    target_components: []
    consumer:
        name: controller.consumer.Consumer
        kwargs:
          incoming_topic: NEW_REPORT
          group_id: report_sync_app
          bootstrap_servers:
            - "localhost:9092"

    publisher:
        name: controller.publisher.Publisher
        kwargs:
          outgoing_topic: SYNCED_REPORT
          bootstrap_servers:
            - "localhost:9092"
    watchers: []
    logging:
        version: 1
        disable_existing_loggers: false
        handlers:
            default:
               level: DEBUG
               class: logging.StreamHandler
               stream: ext://sys.stdout
        root:
            handlers:
                - default
            level: WARNING
        loggers:
            sync_report:
                level: DEBUG
            insights_messaging:
                level: DEBUG
