plugins:
  packages:
    - insights.specs.default
    - controller
    - ccx_rules_ocp.external
    - ccx_rules_ocm
    - pythonjsonlogger
    - pythonjsonlogger.jsonlogger
  configs:
    - name: ccx_ocp_core.config.telemeter.TelemeterServiceConfig
      enabled: false
service:
  extract_timeout:
  extract_tmp_dir:
  format: insights.formats._json.JsonFormat
  target_components: []
  consumer:
    name: controller.consumer.Consumer
    kwargs:
      incoming_topic: platform.upload.testareno
      group_id: ccx_data_pipeline_app
      bootstrap_servers:
        - "kafka:29092"

  downloader:
    name: controller.http_downloader.HTTPDownloader

  publisher:
    name: controller.kafka_publisher.KafkaPublisher
    kwargs:
      outgoing_topic: ccx.ocp.results
      bootstrap_servers:
        - "kafka:29092"
  watchers:
    - name: controller.watchers.stats_watcher.StatsWatcher
      kwargs:
        prometheus_port: 8000
    - name: controller.watchers.cluster_id_watcher.ClusterIdWatcher

  logging:
    version: 1
    disable_existing_loggers: false
    handlers:
      default:
        level: DEBUG
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: json
        filters:
          - context_filter
      logstash:
        level: INFO
        class: logstash.TCPLogstashHandler
        host: "127.0.0.1"
        port: 5000
        version: 1
    formatters:
      brief:
        format: "%(message)s"
      json:
        (): "pythonjsonlogger.jsonlogger.JsonFormatter"
        format: "%(filename)s %(lineno)d %(process)d %(levelname)s %(asctime)s %(name)s %(message)s"
      cloudwatch:
        format: "LEVEL=%(levelname)s; FILENAME=%(filename)s; LINE=%(lineno)d; PID=%(process)d; TIME=%(asctime)s; NAME=%(name)s; HOST=%(hostname)s; MAC_ADDRESS=%(mac_address)s; MESSAGE=%(message)s;"
    filters:
      context_filter:
        (): "controller.log_filter.LogFilter"
    root:
      handlers:
        - default
        - logstash
    loggers:
      insights_messaging:
        level: DEBUG
      insights:
        level: WARNING
      controller:
        level: DEBUG
