plugins:
    packages:
        - insights.specs.default
        - controller
configs: []
service:
    extract_timeout:
    extract_tmp_dir:
    format: insights.formats._json.JsonFormat
    target_components: []
    consumer:
        name: controller.consumer.Consumer
        kwargs:
          incoming_topic: platform.upload.ccx
          group_id: report_sync_app
          bootstrap_servers:
            - "localhost:9092"

    downloader:
        name: controller..minio_downloader.MinioDownloader
        kwargs:
          endpoint: 'minio-service:9000'
          access_key: 'miniouser'
          secret_key_env: 'miniopass'
          secure: false

    publisher:
        name: controller.publisher.Publisher
        kwargs:
          outgoing_topic: platform.results.ccx
          bootstrap_servers:
            - "localhost:9092"
    watchers: []
    logging:
        version: 1
        disable_existing_loggers: false
        handlers:
            default:
               level: DEBUG
               class: logging.StreamHandler
               stream: ext://sys.stdout
        root:
            handlers:
                - default
            level: WARNING
        loggers:
            sync_report:
                level: DEBUG
            insights_messaging:
                level: DEBUG
